### ISSUE TITLE
Menu depth more than 2

### ISSUE THREAD

**Issue by phpSal** [MWDelaney/sage-bootstrap4-navwalker#21]
Is it possible to have more than two level nested menus please ?

SO 

-Home
-Services
   --Engineering
   --AVAC
      ---EU
      ---United States
-Contact US

So be able to Services > AVAC > EU

I can do Services > AVAC but not any deeper.

I know bootstrap 4 allows this so I hope its just a matter of changing the CSS produced by this navwalker.

**Comment by MWDelaney** [comment]
Bootstrap 4 actually doesn't support multiple levels of depth. Here's the article on the Bootstrap 4 navbar component and its supported content:

https://getbootstrap.com/docs/4.0/components/navbar/#supported-content

Unfortunately since Bootstrap 4 doesn't support this, it's out of  scope of this tool. Sorry!

**Comment by phpSal** [comment]
Thank you for replying.

Greatly appreciated.
